#cat *.nocnv_grch38.seg.v2.txt > merge.nocnv_grch38.seg.v2.txt
#mkdir ./New/TCGA
cat ./New/TCGA-BRCA/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-BRCA.merge.nocnv.txt
cat ./New/TCGA-GBM/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-GBM.merge.nocnv.txt
cat ./New/TCGA-OV/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-OV.merge.nocnv.txt
cat ./New/TCGA-LUAD/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-LUAD.merge.nocnv.txt
cat ./New/TCGA-UCEC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-UCEC.merge.nocnv.txt
cat ./New/TCGA-KIRC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-KIRC.merge.nocnv.txt
cat ./New/TCGA-HNSC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-HNSC.merge.nocnv.txt
cat ./New/TCGA-LGG/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-LGG.merge.nocnv.txt
cat ./New/TCGA-THCA/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-THCA.merge.nocnv.txt
cat ./New/TCGA-LUSC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-LUSC.merge.nocnv.txt
cat ./New/TCGA-PRAD/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-PRAD.merge.nocnv.txt
cat ./New/TCGA-SKCM/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-SKCM.merge.nocnv.txt
cat ./New/TCGA-COAD/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-COAD.merge.nocnv.txt
cat ./New/TCGA-STAD/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-STAD.merge.nocnv.txt
cat ./New/TCGA-BLCA/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-BLCA.merge.nocnv.txt
cat ./New/TCGA-LIHC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-LIHC.merge.nocnv.txt
cat ./New/TCGA-CESC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-CESC.merge.nocnv.txt
cat ./New/TCGA-KIRP/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-KIRP.merge.nocnv.txt
cat ./New/TCGA-SARC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-SARC.merge.nocnv.txt
cat ./New/TCGA-LAML/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-LAML.merge.nocnv.txt
cat ./New/TCGA-PAAD/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-PAAD.merge.nocnv.txt
cat ./New/TCGA-ESCA/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-ESCA.merge.nocnv.txt
cat ./New/TCGA-PCPG/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-PCPG.merge.nocnv.txt
cat ./New/TCGA-READ/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-READ.merge.nocnv.txt
cat ./New/TCGA-TGCT/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-TGCT.merge.nocnv.txt
cat ./New/TCGA-THYM/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-THYM.merge.nocnv.txt
cat ./New/TCGA-KICH/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-KICH.merge.nocnv.txt
cat ./New/TCGA-ACC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-ACC.merge.nocnv.txt
cat ./New/TCGA-MESO/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-MESO.merge.nocnv.txt
cat ./New/TCGA-UVM/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-UVM.merge.nocnv.txt
cat ./New/TCGA-DLBC/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-DLBC.merge.nocnv.txt
cat ./New/TCGA-UCS/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-UCS.merge.nocnv.txt
cat ./New/TCGA-CHOL/*.nocnv_grch38.seg.v2.txt > ./New/TCGA/TCGA-CHOL.merge.nocnv.txt
