#需要在命令行执行
gunzip ./Raw/TCGA-BRCA/*.FPKM.txt.gz
gunzip ./Raw/TCGA-GBM/*.FPKM.txt.gz
gunzip ./Raw/TCGA-OV/*.FPKM.txt.gz
gunzip ./Raw/TCGA-LUAD/*.FPKM.txt.gz
gunzip ./Raw/TCGA-UCEC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-KIRC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-HNSC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-LGG/*.FPKM.txt.gz
gunzip ./Raw/TCGA-THCA/*.FPKM.txt.gz
gunzip ./Raw/TCGA-LUSC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-PRAD/*.FPKM.txt.gz
gunzip ./Raw/TCGA-SKCM/*.FPKM.txt.gz
gunzip ./Raw/TCGA-COAD/*.FPKM.txt.gz
gunzip ./Raw/TCGA-STAD/*.FPKM.txt.gz
gunzip ./Raw/TCGA-BLCA/*.FPKM.txt.gz
gunzip ./Raw/TCGA-LIHC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-CESC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-KIRP/*.FPKM.txt.gz
gunzip ./Raw/TCGA-SARC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-LAML/*.FPKM.txt.gz
gunzip ./Raw/TCGA-PAAD/*.FPKM.txt.gz
gunzip ./Raw/TCGA-ESCA/*.FPKM.txt.gz
gunzip ./Raw/TCGA-PCPG/*.FPKM.txt.gz
gunzip ./Raw/TCGA-READ/*.FPKM.txt.gz
gunzip ./Raw/TCGA-TGCT/*.FPKM.txt.gz
gunzip ./Raw/TCGA-THYM/*.FPKM.txt.gz
gunzip ./Raw/TCGA-KICH/*.FPKM.txt.gz
gunzip ./Raw/TCGA-ACC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-MESO/*.FPKM.txt.gz
gunzip ./Raw/TCGA-UVM/*.FPKM.txt.gz
gunzip ./Raw/TCGA-DLBC/*.FPKM.txt.gz
gunzip ./Raw/TCGA-UCS/*.FPKM.txt.gz
gunzip ./Raw/TCGA-CHOL/*.FPKM.txt.gz
