#merge DNA methylation data
mkdir ./New/TCGA
cat ./New/TCGA-BRCA/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-BRCA.merge.dnamethy.txt
cat ./New/TCGA-GBM/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-GBM.merge.dnamethy.txt
cat ./New/TCGA-OV/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-OV.merge.dnamethy.txt
cat ./New/TCGA-LUAD/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-LUAD.merge.dnamethy.txt
cat ./New/TCGA-UCEC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-UCEC.merge.dnamethy.txt
cat ./New/TCGA-KIRC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-KIRC.merge.dnamethy.txt
cat ./New/TCGA-HNSC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-HNSC.merge.dnamethy.txt
cat ./New/TCGA-LGG/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-LGG.merge.dnamethy.txt
cat ./New/TCGA-THCA/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-THCA.merge.dnamethy.txt
cat ./New/TCGA-LUSC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-LUSC.merge.dnamethy.txt
cat ./New/TCGA-PRAD/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-PRAD.merge.dnamethy.txt
cat ./New/TCGA-SKCM/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-SKCM.merge.dnamethy.txt
cat ./New/TCGA-COAD/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-COAD.merge.dnamethy.txt
cat ./New/TCGA-STAD/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-STAD.merge.dnamethy.txt
cat ./New/TCGA-BLCA/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-BLCA.merge.dnamethy.txt
cat ./New/TCGA-LIHC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-LIHC.merge.dnamethy.txt
cat ./New/TCGA-CESC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-CESC.merge.dnamethy.txt
cat ./New/TCGA-KIRP/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-KIRP.merge.dnamethy.txt
cat ./New/TCGA-SARC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-SARC.merge.dnamethy.txt
cat ./New/TCGA-LAML/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-LAML.merge.dnamethy.txt
cat ./New/TCGA-PAAD/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-PAAD.merge.dnamethy.txt
cat ./New/TCGA-ESCA/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-ESCA.merge.dnamethy.txt
cat ./New/TCGA-PCPG/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-PCPG.merge.dnamethy.txt
cat ./New/TCGA-READ/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-READ.merge.dnamethy.txt
cat ./New/TCGA-TGCT/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-TGCT.merge.dnamethy.txt
cat ./New/TCGA-THYM/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-THYM.merge.dnamethy.txt
cat ./New/TCGA-KICH/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-KICH.merge.dnamethy.txt
cat ./New/TCGA-ACC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-ACC.merge.dnamethy.txt
cat ./New/TCGA-MESO/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-MESO.merge.dnamethy.txt
cat ./New/TCGA-UVM/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-UVM.merge.dnamethy.txt
cat ./New/TCGA-DLBC/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-DLBC.merge.dnamethy.txt
cat ./New/TCGA-UCS/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-UCS.merge.dnamethy.txt
cat ./New/TCGA-CHOL/*.gdc_hg38.txt.core.txt > ./New/TCGA/TCGA-CHOL.merge.dnamethy.txt
